apiVersion: v1
kind: Pod
metadata:
  name: db-restore-pod
  namespace: placeholder
  labels:
    app: db-restore
spec:
  containers:
  - name: db-restore
    image: centher/gitflow:dblatest
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  imagePullSecrets:
  - name: gitflow-pull-secret
  restartPolicy: Always 
